### ISSUE TITLE
[Bug]: ERROR STATUS 502

### ISSUE THREAD

**Issue by Dacooa** [codeSTACKr/minter-dapp#49]
### Version

- [X] Yes

### General Question

- [X] No

### What happened?

A bug happened! It won't let me upload metadat
![Screenshot (24)](https://user-images.githubusercontent.com/102386435/164549645-73fbe5d2-6fa5-456d-a9bc-541d4238ced6.png)
a

### What have you tried?

I Googled and asked the community in the discord server but could not find a solution.

### Protect your information

- [X] I Agree

**Comment by NotGettingLeftBehind** [comment]
I am having the same error 502. I did the upload_files command and it uploads a lot of files, but stops with the error 502. I looked up the error and it says it's a bad gateway code. I connected to the latest version of the minter dapp that says it fixes the error. No luck.

**Comment by NotGettingLeftBehind** [comment]
So, it looks like it's a timed out error on the server. I tried to run the code again for the third time, but I had to open a new terminal. It shows how some files were uploaded successfully and starts trying again.

**Comment by Dacooa** [comment]
I can upload the files just fine but it is the metadata will not upload for me no matter what I do.  I even when back and through old threads and attempt to fix the problem that way.

**Comment by NotGettingLeftBehind** [comment]
Did you figure this out? I am having the same error on uploading the metadata. I figured out the 502 issue for uploading files, but the same fix doesn't work for metadata.

**Comment by NotGettingLeftBehind** [comment]
Hey Dacooa, I figured it out. Completely close the open terminal, Minter Dapp and Visual Code. Re-open both. Open new terminal. Run the commands over for cd backend, npm i, and npm run upload_metadata. This just worked for me. I hope it works for you!

**Comment by Dacooa** [comment]
I tried that a few times.  I will try restarting computer and reopening the programs once again when I get home but I feel like I exhausted all my resources.

**Comment by NotGettingLeftBehind** [comment]
The only other advise I can offer (because I am new to coding) is to double check you are using the v0.0.2 release. This is the new release that says the 502 issue with metadata is fixed. However, I still had issues and had to try three times to get it to work and finally restarted everything to get it to work. Plus, I tried doing this with downloading the Minter Dapp zip file and was not able to move forward until I forked the code and started all over again. I know it's frustrating. Hope you can get the help you need to move forward with your project.

**Comment by Dacooa** [comment]
I am using the correct version.  it's still not working and I really don't wanna re-upload my nfts to ifps.  I have a collection of 24k and it took three days of re running the uploading the files over and over again.  I will keep trying different things I guess

**Comment by Dacooa** [comment]
Created a new fork, transfered the files over and I am still getting the same problem.  This is getting tiresome.

**Comment by HV786** [comment]
I had the same error. I was not going for the option of revealing the NFTs so I put 'false' in the Generic metadata field & "Unknown" for the following options as instructed. I run the same command I got hit by error 502, I was not sure why I was getting this error as I did everything as instructed. Then I changed the "Unknown" to null and again hit the command and it got through.

-------------------
Final variation
--------------------
const GENERIC = false; // Set to true if you want to upload generic metas and reveal the real NFTs in the future
const GENERIC_TITLE = CONTRACT_NAME; // Replace with what you want the generic titles to say if you want it to be different from the contract name.
const GENERIC_DESCRIPTION = null; // Replace with what you want the generic descriptions to say.
const GENERIC_IMAGE = null; // Replace with your generic image that will display for all NFTs pre-reveal.
------------------

If you similar condition then please try this and see if it works for you too.

**Comment by Dacooa** [comment]
I was planning on doing a reveal.

**Comment by Dacooa** [comment]
is it possible to move forward without uploading the metadata.  what happens if I don't upload the metadata

**Comment by Dacooa** [comment]
I don't understand how I am suppose to get help on the discord community if I can't communicate with the server or anyone on it.

**Comment by Kaiyun6592** [comment]
I solved the problem same as you! just copy package.json into your minter-dapp folder , re-open terminal then cd backend, npm i, and npm run upload_metadata

**Comment by Kaiyun6592** [comment]
copy this

**Comment by Dacooa** [comment]
it didn't work for me...  I even went as far as to reformat my computer.  I literally tried everything.  this is the only thing that doesn't work for me.

**Comment by Dacooa** [comment]
I guess i will try to continue to spam it until something actually happens.  Nothing works and I been stuck on this for two weeks and my collection is a month late.

**Comment by Cisxy** [comment]
had same problem i ran this: npm audit fix and then tried it again then it worked.

**Comment by Dacooa** [comment]
Sadly this didn't work either, I so lost on what kind but stopping me from finishing my collection.

**Comment by Unprecedentedclub** [comment]
I am facing the same issue any help so far.
